# Generated by Django 5.1.3 on 2024-11-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_sno_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sno',
            field=models.IntegerField(default=0),
        ),
    ]
