# Generated by Django 5.1.3 on 2024-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
