# Generated by Django 5.1.3 on 2024-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_id_alter_product_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sno',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
