# Generated by Django 5.1.3 on 2024-11-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_serial_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
