# Generated by Django 5.1.3 on 2024-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='product',
            name='sno',
            field=models.CharField(default='UNKNOWN', max_length=255, unique=True),
        ),
    ]
