# Generated by Django 5.1.3 on 2024-11-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sno',
            field=models.IntegerField(max_length=255, unique=True),
        ),
    ]
