# Generated by Django 5.1.3 on 2024-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sno',
            field=models.IntegerField(unique=True),
        ),
    ]
