# Generated by Django 5.1.3 on 2024-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_orders_product_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
