# Generated by Django 5.1.3 on 2024-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_orders_products_delete_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.FloatField(default=0, max_length=20),
        ),
    ]
