# Generated by Django 5.1.3 on 2024-12-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
