# Generated by Django 5.1.3 on 2024-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
