# Generated by Django 5.1.3 on 2024-12-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='zipcode',
            field=models.PositiveIntegerField(default='123'),
            preserve_default=False,
        ),
    ]
